<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="EAttribute" eSuperTypes="Ecore.ecore#//EStructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributeType" lowerBound="1"
        eType="ecore:EClass Ecore.ecore#//EDataType" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAnnotation" eSuperTypes="Ecore.ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EStringToStringMapEntry" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eModelElement" eType="ecore:EClass Ecore.ecore#//EModelElement"
        transient="true" resolveProxies="false" eOpposite="Ecore.ecore#//EModelElement/eAnnotations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EObject" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass" eSuperTypes="Ecore.ecore#//EClassifier">
    <eOperations name="isSuperTypeOf" eType="ecore:EDataType Ecore.ecore#//EBoolean">
      <eParameters name="someClass" eType="ecore:EClass Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="getFeatureCount" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    <eOperations name="getEStructuralFeature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature">
      <eParameters name="featureID" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    </eOperations>
    <eOperations name="getFeatureID" eType="ecore:EDataType Ecore.ecore#//EInt">
      <eParameters name="feature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature"/>
    </eOperations>
    <eOperations name="getEStructuralFeature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature">
      <eParameters name="featureName" eType="ecore:EDataType Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="getOperationCount" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    <eOperations name="getEOperation" eType="ecore:EClass Ecore.ecore#//EOperation">
      <eParameters name="operationID" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    </eOperations>
    <eOperations name="getOperationID" eType="ecore:EDataType Ecore.ecore#//EInt">
      <eParameters name="operation" eType="ecore:EClass Ecore.ecore#//EOperation"/>
    </eOperations>
    <eOperations name="getOverride" eType="ecore:EClass Ecore.ecore#//EOperation">
      <eParameters name="operation" eType="ecore:EClass Ecore.ecore#//EOperation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperTypes" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EClass" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOperations" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EOperation" containment="true" resolveProxies="false"
        eOpposite="Ecore.ecore#//EOperation/eContainingClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllAttributes" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EAttribute" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllReferences" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EReference" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReferences" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EReference" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributes" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EAttribute" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllContainments" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EReference" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllOperations" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EOperation" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllStructuralFeatures"
        upperBound="-1" eType="ecore:EClass Ecore.ecore#//EStructuralFeature" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllSuperTypes" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EClass" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eIDAttribute" eType="ecore:EClass Ecore.ecore#//EAttribute"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eStructuralFeatures" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EStructuralFeature" containment="true" resolveProxies="false"
        eOpposite="Ecore.ecore#//EStructuralFeature/eContainingClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericSuperTypes" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EGenericType" unsettable="true" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllGenericSuperTypes"
        upperBound="-1" eType="ecore:EClass Ecore.ecore#//EGenericType" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassifier" abstract="true" eSuperTypes="Ecore.ecore#//ENamedElement">
    <eOperations name="isInstance" eType="ecore:EDataType Ecore.ecore#//EBoolean">
      <eParameters name="object" eType="ecore:EDataType Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getClassifierID" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClassName" eType="ecore:EDataType Ecore.ecore#//EString"
        volatile="true" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClass" changeable="false"
        volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType Ecore.ecore#//EJavaObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceTypeName" eType="ecore:EDataType Ecore.ecore#//EString"
        volatile="true" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="ecore:EClass Ecore.ecore#//EPackage"
        changeable="false" transient="true" eOpposite="Ecore.ecore#//EPackage/eClassifiers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameters" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//ETypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDataType" eSuperTypes="Ecore.ecore#//EClassifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializable" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEnum" eSuperTypes="Ecore.ecore#//EDataType">
    <eOperations name="getEEnumLiteral" eType="ecore:EClass Ecore.ecore#//EEnumLiteral">
      <eParameters name="name" eType="ecore:EDataType Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="getEEnumLiteral" eType="ecore:EClass Ecore.ecore#//EEnumLiteral">
      <eParameters name="value" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    </eOperations>
    <eOperations name="getEEnumLiteralByLiteral" eType="ecore:EClass Ecore.ecore#//EEnumLiteral">
      <eParameters name="literal" eType="ecore:EDataType Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eLiterals" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EEnumLiteral" containment="true" resolveProxies="false"
        eOpposite="Ecore.ecore#//EEnumLiteral/eEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEnumLiteral" eSuperTypes="Ecore.ecore#//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" eType="ecore:EDataType Ecore.ecore#//EEnumerator"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="ecore:EDataType Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eEnum" eType="ecore:EClass Ecore.ecore#//EEnum"
        changeable="false" transient="true" resolveProxies="false" eOpposite="Ecore.ecore#//EEnum/eLiterals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFactory" eSuperTypes="Ecore.ecore#//EModelElement">
    <eOperations name="create" eType="ecore:EClass Ecore.ecore#//EObject">
      <eParameters name="eClass" eType="ecore:EClass Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="createFromString" eType="ecore:EDataType Ecore.ecore#//EJavaObject">
      <eParameters name="eDataType" eType="ecore:EClass Ecore.ecore#//EDataType"/>
      <eParameters name="literalValue" eType="ecore:EDataType Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="convertToString" eType="ecore:EDataType Ecore.ecore#//EString">
      <eParameters name="eDataType" eType="ecore:EClass Ecore.ecore#//EDataType"/>
      <eParameters name="instanceValue" eType="ecore:EDataType Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" lowerBound="1"
        eType="ecore:EClass Ecore.ecore#//EPackage" transient="true" resolveProxies="false"
        eOpposite="Ecore.ecore#//EPackage/eFactoryInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EModelElement" abstract="true">
    <eOperations name="getEAnnotation" eType="ecore:EClass Ecore.ecore#//EAnnotation">
      <eParameters name="source" eType="ecore:EDataType Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAnnotations" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EAnnotation" containment="true" resolveProxies="false"
        eOpposite="Ecore.ecore#//EAnnotation/eModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENamedElement" abstract="true" eSuperTypes="Ecore.ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObject">
    <eOperations name="eClass" eType="ecore:EClass Ecore.ecore#//EClass"/>
    <eOperations name="eIsProxy" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eOperations name="eResource" eType="ecore:EDataType Ecore.ecore#//EResource"/>
    <eOperations name="eContainer" eType="ecore:EClass Ecore.ecore#//EObject"/>
    <eOperations name="eContainingFeature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature"/>
    <eOperations name="eContainmentFeature" eType="ecore:EClass Ecore.ecore#//EReference"/>
    <eOperations name="eContents">
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass Ecore.ecore#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="eAllContents">
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//ETreeIterator">
        <eTypeArguments eClassifier="ecore:EClass Ecore.ecore#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="eCrossReferences">
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass Ecore.ecore#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="eGet" eType="ecore:EDataType Ecore.ecore#//EJavaObject">
      <eParameters name="feature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eGet" eType="ecore:EDataType Ecore.ecore#//EJavaObject">
      <eParameters name="feature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature"/>
      <eParameters name="resolve" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="eSet">
      <eParameters name="feature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature"/>
      <eParameters name="newValue" eType="ecore:EDataType Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="eIsSet" eType="ecore:EDataType Ecore.ecore#//EBoolean">
      <eParameters name="feature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters name="feature" eType="ecore:EClass Ecore.ecore#//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eInvoke" eType="ecore:EDataType Ecore.ecore#//EJavaObject"
        eExceptions="ecore:EDataType Ecore.ecore#//EInvocationTargetException">
      <eParameters name="operation" eType="ecore:EClass Ecore.ecore#//EOperation"/>
      <eParameters name="arguments">
        <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EEList">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOperation" eSuperTypes="Ecore.ecore#//ETypedElement">
    <eOperations name="getOperationID" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    <eOperations name="isOverrideOf" eType="ecore:EDataType Ecore.ecore#//EBoolean">
      <eParameters name="someOperation" eType="ecore:EClass Ecore.ecore#//EOperation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" eType="ecore:EClass Ecore.ecore#//EClass"
        changeable="false" transient="true" resolveProxies="false" eOpposite="Ecore.ecore#//EClass/eOperations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameters" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//ETypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eParameters" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EParameter" containment="true" resolveProxies="false"
        eOpposite="Ecore.ecore#//EParameter/eOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eExceptions" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EClassifier" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericExceptions" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EGenericType" unsettable="true" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPackage" eSuperTypes="Ecore.ecore#//ENamedElement">
    <eOperations name="getEClassifier" eType="ecore:EClass Ecore.ecore#//EClassifier">
      <eParameters name="name" eType="ecore:EDataType Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsURI" eType="ecore:EDataType Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" eType="ecore:EDataType Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFactoryInstance" lowerBound="1"
        eType="ecore:EClass Ecore.ecore#//EFactory" transient="true" resolveProxies="false"
        eOpposite="Ecore.ecore#//EFactory/ePackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifiers" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EClassifier" containment="true" eOpposite="Ecore.ecore#//EClassifier/ePackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSubpackages" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EPackage" containment="true" eOpposite="Ecore.ecore#//EPackage/eSuperPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperPackage" eType="ecore:EClass Ecore.ecore#//EPackage"
        changeable="false" transient="true" eOpposite="Ecore.ecore#//EPackage/eSubpackages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EParameter" eSuperTypes="Ecore.ecore#//ETypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOperation" eType="ecore:EClass Ecore.ecore#//EOperation"
        changeable="false" transient="true" resolveProxies="false" eOpposite="Ecore.ecore#//EOperation/eParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReference" eSuperTypes="Ecore.ecore#//EStructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="container" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolveProxies" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOpposite" eType="ecore:EClass Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReferenceType" lowerBound="1"
        eType="ecore:EClass Ecore.ecore#//EClass" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eKeys" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeature" abstract="true"
      eSuperTypes="Ecore.ecore#//ETypedElement">
    <eOperations name="getFeatureID" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    <eOperations name="getContainerClass">
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeable" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatile" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueLiteral" eType="ecore:EDataType Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType Ecore.ecore#//EJavaObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsettable" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" eType="ecore:EClass Ecore.ecore#//EClass"
        changeable="false" transient="true" resolveProxies="false" eOpposite="Ecore.ecore#//EClass/eStructuralFeatures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypedElement" abstract="true" eSuperTypes="Ecore.ecore#//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" eType="ecore:EClass Ecore.ecore#//EClassifier"
        volatile="true" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericType" eType="ecore:EClass Ecore.ecore#//EGenericType"
        volatile="true" unsettable="true" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringToStringMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGenericType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eUpperBound" eType="ecore:EClass Ecore.ecore#//EGenericType"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeArguments" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eRawType" lowerBound="1"
        eType="ecore:EClass Ecore.ecore#//EClassifier" changeable="false" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eLowerBound" eType="ecore:EClass Ecore.ecore#//EGenericType"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameter" eType="ecore:EClass Ecore.ecore#//ETypeParameter"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifier" eType="ecore:EClass Ecore.ecore#//EClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeParameter" eSuperTypes="Ecore.ecore#//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBounds" upperBound="-1"
        eType="ecore:EClass Ecore.ecore#//EGenericType" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBigDecimal" instanceClassName="java.math.BigDecimal">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#decimal"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBigInteger" instanceClassName="java.math.BigInteger">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#integer"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBoolean" instanceClassName="boolean">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#boolean"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBooleanObject" instanceClassName="java.lang.Boolean">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EBoolean"/>
      <details key="name" value="EBoolean:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByte" instanceClassName="byte">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#byte"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByteArray" instanceClassName="byte[]">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#hexBinary"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByteObject" instanceClassName="java.lang.Byte">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EByte"/>
      <details key="name" value="EByte:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EChar" instanceClassName="char"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ECharacterObject" instanceClassName="java.lang.Character">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EChar"/>
      <details key="name" value="EChar:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDate" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDiagnosticChain" instanceClassName="org.eclipse.emf.common.util.DiagnosticChain"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDouble" instanceClassName="double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#double"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDoubleObject" instanceClassName="java.lang.Double">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EDouble"/>
      <details key="name" value="EDouble:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EEList" instanceClassName="org.eclipse.emf.common.util.EList"
      serializable="false">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EEnumerator" instanceClassName="org.eclipse.emf.common.util.Enumerator"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMap" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMapEntry" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap$Entry"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFloat" instanceClassName="float">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#float"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFloatObject" instanceClassName="java.lang.Float">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EFloat"/>
      <details key="name" value="EFloat:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EInt" instanceClassName="int">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#int"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EIntegerObject" instanceClassName="java.lang.Integer">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EInt"/>
      <details key="name" value="EInt:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EJavaClass" instanceClassName="java.lang.Class">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EJavaObject" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ELong" instanceClassName="long">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#long"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ELongObject" instanceClassName="java.lang.Long">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="ELong"/>
      <details key="name" value="ELong:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EMap" instanceClassName="java.util.Map"
      serializable="false">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EResource" instanceClassName="org.eclipse.emf.ecore.resource.Resource"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EShort" instanceClassName="short">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#short"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EShortObject" instanceClassName="java.lang.Short">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EShort"/>
      <details key="name" value="EShort:Object"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EString" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.w3.org/2001/XMLSchema#string"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ETreeIterator" instanceClassName="org.eclipse.emf.common.util.TreeIterator"
      serializable="false">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EInvocationTargetException" instanceClassName="java.lang.reflect.InvocationTargetException"
      serializable="false"/>
</ecore:EPackage>
